### ISSUE TITLE
Update to current version

### ISSUE THREAD

**Issue by tdymel** [sd2k/rocket_prometheus#2]
Hey!
Cool plugin! It works like a charm. Unfortunately tools like Grafana dont support old Prometheus versions as it seems.

The current API specification is prometheus 1.8 I believe. It would be nice if you would implement instant queries (i.e., Prometheus 2.14 specification) such that Grafana works :)

Cheers!

**Comment by sd2k** [comment]
Hi - thanks a lot, glad it's working. Could you describe your issue with Grafana a little more? 

Currently I'm just making use of the [prometheus](https://github.com/pingcap/rust-prometheus) crate which does most of the work; `rocket_prometheus` just simplifies capturing some standard HTTP metrics for Rocket and provides an endpoint to expose those metrics.

**Comment by tdymel** [comment]
Hi!
As it seems, this plugin only provides a single endpoint,e.g. /metrics.
However, when configuring Graphana for a prometheus endpoint, it attempts to use queries like /metrics/api/query?query= and many more.
Naturally the endpoint cant respond to this. 
The described queries are so called instant queries from the newer prometheus specification. The prometheus crate that you use does not do anything wrong, it adheres the specification, however your crate does not configure the endpoints for these instant queries that newer version of graphana seem to require.

Cheers!

**Comment by sd2k** [comment]
Ah, this crate only provides an endpoint (`/metrics`) to be scraped by Prometheus itself - it's not meant to be queried by Grafana. I run this with the Prometheus/Alertmanager/Grafana all running together, with Prometheus configured to scrape the `/metrics` endpoint of my app every ~10s. It's then Prometheus which serves Grafana's queries on the `/api/query?query=...` endpoint.

This crate is therefore similar to e.g. [prometheus-flask-exporter](https://pypi.org/project/prometheus-flask-exporter) or [express-prom-bundle](https://github.com/jochen-schweizer/express-prom-bundle).

Does that help?

**Comment by tdymel** [comment]
That helped, sorry, I totally missunderstood how this stuff works :)

Here are the changes: https://github.com/Geigerkind/Rusty-Template

Cheers and merry christmas!
