### ISSUE TITLE
Is there a way to exclude /metrics from the reporting

### ISSUE THREAD

**Issue by gemcoder21** [sd2k/rocket_prometheus#22]
Is there a way to exclude specific routes like `metrics` to exclude from the prometheus stats?

**Comment by sd2k** [comment]
Not currently, no. I'd accept a PR to add a method to `PrometheusMetrics` to include/exclude routes, possibly based on a closure accepting a `Request`? It would probably require us to `Box` the closure which adds an allocation and pointer chase, but that's unlikely to be a huge issue.
